protected/modules/shop/controllers/CartController.php
<?php

class CartController extends Controller
{

  public $layout = '//layouts/main';

  public function init(){
      if(!isset(Yii::app()->session['cart'])){
          echo 'session expirada';
      }
  }

  public function accessRules()
  {
    return 
      array(
        /*array(
          'allow',  // allow all users to perform 'index' and 'view' actions
          'actions'=>array('index','view','removeajax', 'add', 'remove', 'display', 'executePayment'),
          'users'=>array('*'),
        ),*/
        array(
          'allow', // deny all users
          'users' => array('*')
      )
    );
  }

	private $itemList=array();

	public function actionAdd($id)
	{
    //unset(Yii::app()->session['cart']); return; //to remove session key

        /*
TODO: validar in stock
        */
    $session=Yii::app()->session;

		if($session['cart']==null)
		{
		  echo 'save order by session expire';
          //throw new CException('session expire');

		  $session['cart']=array();
		}

		$cartBo = new CartBO;
    $res=$cartBo->getItem($id);

    $itemList=$session['cart'];
    //echo var_dump($itemList); return;
    $itemList = $this->updateTotal($res, $itemList);//update qty if already exists

    $session['cart']=$itemList;

    //echo var_dump($session['cart']); return;

        //return isset($res);//boolean
	}

  public function actionAddItemTest()
  {
    $this->actionAdd(11);
    $this->actionAdd(12);
    $this->actionAdd(13);
    $this->actionAdd(15);
    $this->actionAdd(16);
    $this->actionAdd(17);
  }

	private function updateTotal($item, $itemList)
	{
	  $existe=false;

    for ($pos=0; $pos < sizeof($itemList); $pos++) {
      if($item->id==$itemList[$pos]->id){
        $itemList[$pos]->qty = $itemList[$pos]->qty + 1;
        $itemList[$pos]->total = $itemList[$pos]->qty*$itemList[$pos]->price;
        $existe=true;
      }
    }

    if(!$existe)
    {
      array_push($itemList, $item);
    }

    return $itemList;
	}

/*
*@pos es la posicion del item en el array de la session,
viene en el post de la request
*/
	public function actionRemove($pos)
	{

    try
    {
      $newArr=array();
      $session=Yii::app()->session;
      $arr=$session['cart'];

      for ($key=0; $key < sizeof($arr); $key++) {
        if($key!=$pos)
        {
          array_push($newArr, $arr[$key]);
        }
      }

      $session['cart']=$newArr;
      //echo 'ok';
      //return 'OK';
    }
    catch(CException $e)
    {
      //echo 'err';
      //return 'ERR';
    }
    //throw new CException(Yii::t('yii','CHttpSession.cookieMode can only be "none", "allow" or "only".'));
	}

  /**
  *Despliega el carrito de la compra
  *@param nu: es nuevo usuario
  */
	public function actionDisplay($nu=false)
	{
    $this->pageTitle="SIDIC - Carrito";
 	  $session=Yii::app()->session;
    $fiscalData;
    if(!Yii::app()->user->isGuest){
      $fiscalData=Fiscal::model()->findAll('userid='.Yii::app()->user->id)[0];
      $fiscalData=$fiscalData!=null?$fiscalData:new Fiscal;
    }else{
      $fiscalData=new Fiscal;
    }

    $cartBO = new CartBO;

	  $this->render('display',
                   array(
                      'cart'=>$session['cart'],
                      'total'=>$cartBO->getTotalToPay(),
                      'isNewUser'=>$nu,
                      'fiscalData'=>$fiscalData
                    ));
	}

  public function actionExecutePayment(){
    include("sample/payments/test.php");
  }

	public function actionSave(){
	  return null;
	}

  public function inStock($item)
  {
    $cartBo = new CartBO();
    $item = new Item();
    $item->id=1;

    return $cartBo->inStock($item, Null);
  }

  public function actionRemoveAjax($pos)
  {
    $this->actionRemove($pos);

    $session=Yii::app()->session;
    //$total=$this->totalToPay();//total a pagar para mostrar en el summary
    $total=0.00;

//echo json_encode($session['cart']);
    $cartBO = new CartBO;
    $this->renderPartial(
                    '_display',
                    array(
                      'cart'=>$session['cart'],
                      'total'=>$cartBO->getTotalToPay(),
                    ), false, false);
  }

}

protected/modules/shop/views/cart/_display.php
    <?php 
      $session=Yii::app()->session;
      if($session['cart']==null)
      {
        echo 'Volver a la lista de paquetes.';
      }
    ?>

    <?php 

    for ($pos=0; $pos < sizeof($cart); $pos++) {
  ?>
    
    <div class="row">
      <div class="col-md-2">
        <?php echo $cart[$pos]->name; ?>
      </div>
      <div class="col-md-4">
        <?php echo $cart[$pos]->description; ?>
      </div>
      <div class="col-md-2">
        <?php echo number_format($cart[$pos]->price, 2, '.', ','); ?>
      </div>
      <div class="col-md-1">
        <?php echo number_format($cart[$pos]->total, 2, '.', ','); ?>
      </div>
      <div class="col-md-1 text-right">
  <?php 
        /*echo CHtml::ajaxLink("remove item",
                                CController::createUrl('cart/removeajax&pos='.$pos), 
                                array('update' => '#cart'),
                              );*/

        echo CHtml::ajaxLink(
          $text = '&nbsp;&nbsp;quitar', 
          $url = CController::createUrl('cart/RemoveAjax/pos/'.$pos), 
          $ajaxOptions=array (
              'type'=>'GET',
              //'dataType'=>'json',
              'success'=>'function(html){
                  jQuery("#cart").html(html);
                  jQuery("#btnContinuar").remove();
                }'
              ), 
          $htmlOptions=array ()
        );

  ?>

      </div>
    </div>
<?php }?>

protected/modules/shop/views/cart/_minilogin.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
  'Login',
);
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
  'id'=>'login-form',
  'enableAjaxValidation'=>false,
  'htmlOptions' => array('enctype'=>'multipart/form-data'),
)); ?>

  <?php echo $form->textField($model,'username'); ?>

  <?php echo $form->passwordField($model,'password'); ?>

  <div id="error"></div>
  <?php 
      echo CHtml::ajaxSubmitButton('Ingresar',
                                    CController::createUrl('/site/login'), 
                                    $ajaxOptions=array (
                                      'success'=>'function(data){
                                          jQuery("#error").html(data); 

                                          if(data=="")
                                            window.location="'.CController::createUrl('cart/display').'";
                                        }'
                                      )
                                    );

   ?>

<?php $this->endWidget(); ?>

</div><!-- form -->
<!-- </div> -->

protected/modules/shop/views/cart/_summary.php
      
Resumen<br/>
<?php echo number_format($total, 2, '.', ','); ?>
<br><br><br>
<?php 

?>

protected/modules/shop/views/cart/display.php
<?php
  $this->breadcrumbs=array(
  	//$cart->title,
  	'cart'
  );
?>

  <div class="row">
    <h3>Resumen de su carrito</h3>
  </div>

  <div class="row">
    <div class="col-md-9 col-lg-9">
      <div id="cart">
        <?php 
          $this->renderPartial('_display',
                                array(
                                  'cart'=>$cart,
                                  'total'=>$total,
                                ));
        ?>
      </div>
    </div>
    <div class="col-md-3 col-lg-3">
        <?php $this->renderPartial('_summary', array(
                                  'cart'=>$cart,
                                  'total'=>$total,
                                )); 
        ?>
    </div>
  </div>

  <div class="row">
      <div class="col-md-9 col-lg-9">
      </div>
  <?php if($isNewUser==false): ?>
      <div class="col-md-3 col-lg-3">
        <?php $url=Yii::app()->createUrl('user/register'); ?>
        <a href="<?php echo $url; ?>" type="button" id="btnContinuar" class="btn btn-primary btn-sm">
          Pagar
        </a>        
      </div>
  <?php endif; ?>
  </div>

  <div class="row">
  <?php if($isNewUser): ?>
  <?php 
    $this->renderPartial('//user/billingform', array('model'=>$fiscalData));
  ?>
  <?php endif; ?>
  </div>

<!-- sección de metodos de pago -->
  <div class="row">
  <?php 
    $this->renderPartial('/payment/payment');
  ?>
  </div>

protected/modules/shop/views/cart/thank.php
thank you