protected/models/Supplier.php
<?php

/**
 * This is the model class for table "supplier".
 *
 * The followings are the available columns in table 'supplier':
 * @property integer $supplier_id
 * @property string $code
 * @property string $name
 * @property string $rfc
 * @property string $address
 * @property string $patronal_record
 * @property string $agent
 * @property string $phone
 * @property string $email
 * @property string $bank
 * @property string $account
 * @property string $clabe
 * @property string $created
 * @property string $updated
 * @property string $active
 */
class Supplier extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'supplier';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, rfc, address, code, phone, email', 'required'),
			array('code, rfc, patronal_record, email', 'length', 'max'=>50),
			array('phone', 'length', 'max'=>30),
			array('email', 'email'),
			array('name, address, agent', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('supplier_id, code, name, rfc, address, patronal_record, agent', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'supplier_id' => 'ID',
			'code' => 'Clave',
			'name' => 'Nombre Comercial',
			'rfc' => 'RFC',
			'address' => 'Domicilio',
			'patronal_record' => 'Registro Patronal',
			'agent' => 'Representante',
			'phone' => 'Teléfono',
			'email' => 'Correo',
			'bank' => 'Banco',
			'account' => 'Cuenta',
			'clabe' => 'CLABE',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('supplier_id',$this->supplier_id);
		$criteria->compare('code',$this->code,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('rfc',$this->rfc,true);
		$criteria->compare('address',$this->address,true);
		$criteria->compare('patronal_record',$this->patronal_record,true);
		$criteria->compare('agent',$this->agent,true);

        $licensekey=Yii::app()->user->getState('licensekey');
        $criteria->addCondition("licensekey='".$licensekey."'");

		return new CActiveDataProvider($this, array(
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['supplierPerPage'],
			),
			'criteria'=>$criteria,
		));
	}

	public static function genId(){
		$licensekey=Yii::app()->user->getState('licensekey');
		$q="SELECT COALESCE(MAX(supplier_id), 0) + 1 FROM supplier WHERE licensekey = '$licensekey'";
		$r=Yii::app()->db->createCommand($q)->queryScalar();
		
		return $r;
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Supplier the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

}

protected/controllers/SupplierController.php
<?php

class SupplierController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update', 'admin'),
				'roles'=>array('admin', 'elaborador'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Supplier;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Supplier']))
		{
			$model->attributes=$_POST['Supplier'];
			$model->bank=isset($_POST['Supplier']['bank']) ? $_POST['Supplier']['bank'] : '';
			$model->account=isset($_POST['Supplier']['account']) ? $_POST['Supplier']['account'] : '';
			$model->clabe=isset($_POST['Supplier']['clabe']) ? $_POST['Supplier']['clabe'] : '';
			$model->active=isset($_POST['Supplier']['active']) ? 1 : 0;
			$model->updated=time();
			$model->licensekey=Yii::app()->user->getState('licensekey');
			$model->supplier_id = Supplier::genId();

			if($model->validate()){
			  if($model->save()){
			    $this->redirect(array('admin'));
			  }
			}
		}

		Yii::app()->user->setFlash('created', 'Se ha creado con éxito el proveedor: {$model->name}');

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Supplier']))
		{
			$model->attributes=$_POST['Supplier'];
      $model->bank=isset($_POST['Supplier']['bank']) ? $_POST['Supplier']['bank'] : '';
      $model->account=isset($_POST['Supplier']['account']) ? $_POST['Supplier']['account'] : '';
      $model->clabe=isset($_POST['Supplier']['clabe']) ? $_POST['Supplier']['clabe'] : '';
      $model->active=isset($_POST['Supplier']['active']) ? 1 : 0;
      $model->updated=time();
      
			if($model->save()){
        Yii::app()->user->setFlash('updated', "Se ha actualizado con éxito el proveedor: {$model->name}");
				$this->redirect(array('admin'));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Supplier');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Supplier('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Supplier']))
			$model->attributes=$_GET['Supplier'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Supplier the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$licensekey=Yii::app()->user->getState('licensekey');
		$model=Supplier::model()->findByPk($id);
		
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Supplier $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='supplier-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/supplier/_form.php
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>Proveedores
            <small class="text-muted">Los campos con asterisco son requeridos</small>
            </h2>

           <h2><small class="text-muted">
            <?php 
               if(Yii::app()->user->hasFlash('updated')){
                 echo Yii::app()->user->getFlash('updated');
               }
             ?>            
           </small></h2>               
        </div>
        <div class="col-lg-5 col-md-6 col-sm-12">
            <ul class="breadcrumb float-md-right">
                <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Sidic</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0);">Catálogos</a></li>
                <li class="breadcrumb-item active">Proveedores</li>
            </ul>
        </div>
    </div>
</div>

<div class="container-fluid">
  <div class="row clearfix">
      <div class="col-lg-12 col-md-12 col-sm-12">
          <div class="card">
              <div class="header">
                  <h2></h2>
              </div>
              <div class="body">

                <?php $form=$this->beginWidget('CActiveForm', array(
                  'id'=>'supplier-form',
                  'enableAjaxValidation'=>false,
                  'htmlOptions' => array('enctype'=>'multipart/form-data'),
                )); ?>

                <?php CHtml::$errorContainerTag = 'label'; ?>

                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                      <div class="col-lg-6 col-md-6 col-sm-6">
                        <label for="Supplier_code">*Clave</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->code; ?>" name="Supplier[code]" type="text" id="Supplier_code" class="form-control" placeholder="">
                                <?php echo $form->error($model,'code', array('class'=>'error')); ?>
                            </div>
                        </div>  
                        <label for="Supplier_name">*Nombre</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->name; ?>" name="Supplier[name]" type="text" id="Supplier_name" class="form-control" placeholder="">
                                <?php echo $form->error($model,'name', array('class'=>'error')); ?>
                            </div>
                        </div>  
                        <label for="Supplier_rfc">*RFC</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->rfc; ?>" name="Supplier[rfc]" type="text" id="Supplier_rfc" class="form-control" placeholder="">
                                <?php echo $form->error($model,'rfc', array('class'=>'error')); ?>
                            </div>
                        </div>  
                        <label for="Supplier_address">*Domicilio</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->address; ?>" name="Supplier[address]" type="text" id="Supplier_address" class="form-control" placeholder="">
                                <?php echo $form->error($model,'address', array('class'=>'error')); ?>
                            </div>
                        </div>  
                        <label for="Supplier_patronal_record">Registro patronal</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->patronal_record; ?>" name="Supplier[patronal_record]" type="text" id="Supplier_patronal_record" class="form-control" placeholder="">
                            </div>
                        </div>  

                        <div class="input-group input-group-lg">
                            <div class="demo-switch-title">Activo</div>
                            <div class="switch">
                                <label>
                                    <input type="checkbox" name="Supplier[active]" id="Supplier_active"
                    <?php echo $model->active==1 ? 'checked=""' : '' ?>
                                    >
                                    <span class="lever switch-col-blue"></span></label>
                            </div>
                        </div>
                      </div>
                      <div class="col-lg-6 col-md-6 col-sm-6">
                        <label for="Supplier_agent">Representante</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->agent; ?>" name="Supplier[agent]" type="text" id="Supplier_agent" class="form-control" placeholder="">
                            </div>
                        </div>  

                        <label for="Supplier_phone">*Teléfono</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->phone; ?>" name="Supplier[phone]" type="text" id="Supplier_phone" class="form-control" placeholder="">
                                <?php echo $form->error($model,'phone', array('class'=>'error')); ?>
                            </div>
                        </div>  

                        <label for="Supplier_email">*Correo</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->email; ?>" name="Supplier[email]" type="text" id="Supplier_email" class="form-control" placeholder="">
                                <?php echo $form->error($model,'email', array('class'=>'error')); ?>
                            </div>
                        </div>  

                        <label for="Supplier_bank">Banco</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->bank; ?>" name="Supplier[bank]" type="text" id="Supplier_bank" class="form-control" placeholder="">
                                <?php echo $form->error($model,'bank', array('class'=>'error')); ?>
                            </div>
                        </div>  

                        <label for="Supplier_account">Cuenta</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->account; ?>" name="Supplier[account]" type="text" id="Supplier_account" class="form-control" placeholder="">
                                <?php echo $form->error($model,'account', array('class'=>'error')); ?>
                            </div>
                        </div>  

                        <label for="Supplier_clabe">CLABE</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input value="<?php echo $model->clabe; ?>" name="Supplier[clabe]" type="text" id="Supplier_clabe" class="form-control" placeholder="">
                                <?php echo $form->error($model,'clabe', array('class'=>'error')); ?>
                            </div>
                        </div>  

                      </div>
                    </div>
                </div>


                    <button type="submit" class="btn btn-raised btn-primary m-t-15 waves-effect"><?php echo $model->isNewRecord ? 'Crear' : 'Guardar'; ?></button>
    <?php echo CHtml::link('Cancelar', Yii::app()->createUrl('supplier/admin') ,array('class'=>'btn btn-raised btn-primary m-t-15 waves-effect')); ?>

                  <?php $this->endWidget(); ?>
              </div>
          </div>
      </div>
  </div>
</div>

protected/views/supplier/_search.php
<?php
/* @var $this SupplierController */
/* @var $model Supplier */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'code'); ?>
		<?php echo $form->textField($model,'code',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'rfc'); ?>
		<?php echo $form->textField($model,'rfc',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'address'); ?>
		<?php echo $form->textField($model,'address',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'patronal_record'); ?>
		<?php echo $form->textField($model,'patronal_record',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'agent'); ?>
		<?php echo $form->textField($model,'agent',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/supplier/_view.php
<?php
/* @var $this SupplierController */
/* @var $data Supplier */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('code')); ?>:</b>
	<?php echo CHtml::encode($data->code); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('rfc')); ?>:</b>
	<?php echo CHtml::encode($data->rfc); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('address')); ?>:</b>
	<?php echo CHtml::encode($data->address); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('patronal_record')); ?>:</b>
	<?php echo CHtml::encode($data->patronal_record); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('agent')); ?>:</b>
	<?php echo CHtml::encode($data->agent); ?>
	<br />


</div>

protected/views/supplier/admin.php
<?php
/* @var $this SupplierController */
/* @var $model Supplier */

$this->breadcrumbs=array(
	'Suppliers'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Supplier', 'url'=>array('index')),
	array('label'=>'Create Supplier', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#supplier-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h2>Proveedores</h2>
<?php echo CHtml::link('crear', Yii::app()->createUrl('supplier/create') ,array('class'=>'btn btn-raised btn-primary m-t-15 waves-effect')); ?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'supplier-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'cssFile'=>Yii::app()->theme->baseUrl.'/assets/cgridview/styles.css',
	'columns'=>array(
		'code',
		'name',
		'rfc',
		'patronal_record',
		array(
			'class'=>'CButtonColumn',
			'buttons'=>array(
				'update' => array(
				    //'label'=>'...',     // text label of the button
				    'url'=>'Yii::app()->controller->createUrl("supplier/update",array("id"=>$data->id))',
				    'imageUrl'=>false,  // image URL of the button. If not set or false, a text link is used
				    //'options'=>array('class'=>'btn btn-raised btn-primary m-t-15 waves-effect'), // HTML options for the button tag
				    //'click'=>'...',     // a JS function to be invoked when the button is clicked
				    'visible'=>'true',   // a PHP expression for determining whether the button is visible
				),	
				'delete' => array(
				    //'label'=>'...',     // text label of the button
				    //'url'=>'...',       // a PHP expression for generating the URL of the button
				    //'imageUrl'=>'...',  // image URL of the button. If not set or false, a text link is used
				    //'options'=>array(...), // HTML options for the button tag
				    //'click'=>'...',     // a JS function to be invoked when the button is clicked
				    'visible'=>'false',   // a PHP expression for determining whether the button is visible
				),	
				'view' => array(
				    //'label'=>'...',     // text label of the button
				    //'url'=>'...',       // a PHP expression for generating the URL of the button
				    //'imageUrl'=>'...',  // image URL of the button. If not set or false, a text link is used
				    //'options'=>array(...), // HTML options for the button tag
				    //'click'=>'...',     // a JS function to be invoked when the button is clicked
				    'visible'=>'false',   // a PHP expression for determining whether the button is visible
				)			
			),
		),
	),
)); ?>

protected/views/supplier/create.php
<?php
/* @var $this SupplierController */
/* @var $model Supplier */

$this->breadcrumbs=array(
	'Suppliers'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Supplier', 'url'=>array('index')),
	array('label'=>'Manage Supplier', 'url'=>array('admin')),
);
?>


<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/supplier/index.php
<?php
/* @var $this SupplierController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Suppliers',
);

$this->menu=array(
	array('label'=>'Create Supplier', 'url'=>array('create')),
	array('label'=>'Manage Supplier', 'url'=>array('admin')),
);
?>

<h1>Suppliers</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/supplier/update.php
<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/supplier/view.php
<?php
/* @var $this SupplierController */
/* @var $model Supplier */

$this->breadcrumbs=array(
	'Suppliers'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Supplier', 'url'=>array('index')),
	array('label'=>'Create Supplier', 'url'=>array('create')),
	array('label'=>'Update Supplier', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Supplier', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Supplier', 'url'=>array('admin')),
);
?>

<h1>View Supplier #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'code',
		'name',
		'rfc',
		'address',
		'patronal_record',
		'agent',
	),
)); ?>