protected/models/Project.php
<?php

/**
 * This is the model class for table "project".
 *
 * The followings are the available columns in table 'project':
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $address
 * @property string $location
 */
class Project extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'project';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('code, name, address, location', 'required'),
			array('code, location', 'length', 'max'=>50),
			array('name, address', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('code, name, address, location', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'budgets' => array(self::HAS_MANY, 'Budget', 'projectid'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'code' => 'Código',
			'name' => 'Nombre',
			'address' => 'Dirección',
			'location' => 'Plaza',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.
    /*aqui se hace la consulta tomando en cuenta la relacion que existe entre el usuario y los proyectos y presupuestos*/
    /*ya que algunos usuarios no tienen acceso a todos los proyectos y presupuestos*/

		$criteria=new CDbCriteria;
		$query="
		SELECT rel.id,rel.projectid, rel.budgetid, rel.userid
		,((SELECT COUNT(*) FROM budget WHERE projectid = rel.projectid) = 
		(SELECT COUNT(*) FROM budgetuser_rel WHERE userid = rel.userid AND projectid = rel.projectid )) AS eq
		FROM budgetuser_rel rel
		WHERE userid=".Yii::app()->user->id;

    $projects = Yii::app()->db->createCommand($query)->queryAll();

    $projectIdList="0";
    foreach ($projects as $pro) {
    	if($pro["eq"]==1){
        $projectIdList.=$pro["projectid"].',';
    	}
    }

    if(strlen($projectIdList)>0 && $projectIdList!='0'){
    	$projectIdList.='0';
    }

    $licensekey=Yii::app()->user->getState('licensekey');

    //Se consultan solos los proyectos que le corresponden al usuario según su licencia
		$criteria->compare('code',$this->code,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('address',$this->address,true);
		$criteria->compare('location',$this->location,true);
		$criteria->addCondition('id not in('.$projectIdList.')');
		$criteria->addCondition("licensekey='".$licensekey."'");

		return new CActiveDataProvider($this, array(
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['projectPerPage'],
			),
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Project the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

}

protected/controllers/ProjectController.php
<?php

class ProjectController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='//layouts/admin';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'ajaxOnly + budgetlisthtml + projectListHtml', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update', 'admin','budgetlisthtml','ProjectListHtml'),
                'roles'=>array('admin'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('admin', 'view'),
                'roles'=>array('autorizador', 'elaborador', 'contralor', 'receptor','budgetlisthtml','ProjectListHtml'),
            ),
            array('deny', // allow admin user to perform 'admin' and 'delete' actions
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model=new Project;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Project']))
        {
            $model->attributes=$_POST['Project'];
            $model->licensekey=Yii::app()->user->getState('licensekey');

            if($model->save())
                $this->redirect(Yii::app()->createUrl('project/update', array('id'=>$model->id)));
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Project']))
        {
            $model->attributes=$_POST['Project'];

            if($model->save())
        Yii::app()->user->setFlash('updated', "Se ha actualizado con éxito el proveedor: {$model->name}");
                $this->redirect(array('admin'));
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider=new CActiveDataProvider('Project');
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
          $model=new Project('search');

          $model->unsetAttributes();  // clear any default values
          if(isset($_GET['Project']))
              $model->attributes=$_GET['Project'];

          $this->render('admin',array(
              'model'=>$model,
          ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Project the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=Project::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Project $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='project-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    /**
    *Action que muestra un listado de los presupuestos pertenecientes a un proyecto en formato html
    *este llamado solo es por ajax
    *@id es el id del proyecto
    */
    public function actionBudgetListHtml($id){
      $project=Project::Model()->findByPk($id);
      $budgetList="";
      $index=0;

      foreach ($project->budgets as $budget) {
        $index=$index+1;
        $budgetList.=
        '<div class="row presupuestorow">
          <div class="col-md-8 col-sm-8 col-xs-8 col-lg-8">
            <div class="item">'.$budget->name.'<br></div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4 text-right">
            <input class="budgetcheck" id="bicheck_'.$budget->id.'" onclick="refreshBudgetList(this, '.$id.','.$budget->id.');" name="BudgetAccess['.$index.'][budgetid]" type="checkbox" />
          </div>
        </div>';
      }

      if($budgetList==''){
        $budgetList="SIN PRESUPUESTOS";
      }

      echo $budgetList;
    }

    /**
    *Action que muestra un listado de los projectos en formto html
    *este llamado solo es por ajax
    *@id es el id del proyecto
    */
    public function actionProjectListHtml(){
      $licensekey=Yii::app()->user->getState('licensekey');
      $project=Project::Model()->findAll("licensekey='".$licensekey."'");
      $projectList="";
      $id=0;

      foreach ($project as $item) {
        $id=$id+1;
        $projectList.=
        '<div class="row projectrow" id="user_'.$id.'">
          <div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">
            <div class="item" onclick="getBudgetList('.$item->id.', '."'user_$id'".');">'.$item->name.' ('.sizeof($item->budgets).')<br></div>
          </div>
        </div>';
      }

      echo $projectList;
    }


}

protected/views/project/_form.php
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>Proyecto <?php echo $model->name; ?>
<?php if(!$model->isNewRecord): ?>
  <?php $url = Yii::app()->createUrl('/budget/list').'&id='.$model->id; ?>
  </h2><a href="<?php echo $url; ?>" style="color: #337ab7;text-decoration: none;">Ver presupuestos </a>
<?php endif ?>
              <br/><small class="text-muted">Los campos con asterisco son requeridos</small>
        </div>
        <div class="col-lg-5 col-md-6 col-sm-12">
            <ul class="breadcrumb float-md-right">
                <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Sidic</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0);">Catálogos</a></li>
                <li class="breadcrumb-item active">Proyecto</li>
            </ul>
        </div>
    </div>
</div>

	<div class="row clearfix">
      <div class="col-lg-12 col-md-12 col-sm-12">
          <div class="card">
              <div class="header">
                  <h2></h2>
              </div>
              <div class="body">

<?php $form=$this->beginWidget('CActiveForm', array(
  'id'=>'project-form',
  // Please note: When you enable ajax validation, make sure the corresponding
  // controller action is handling ajax validation correctly.
  // There is a call to performAjaxValidation() commented in generated controller code.
  // See class documentation of CActiveForm for details on this.
  'enableAjaxValidation'=>false,
  'htmlOptions' => array('enctype'=>'multipart/form-data'),
)); ?>

<?php CHtml::$errorContainerTag = 'label'; ?>

  <label for="Project_code">*Clave</label>
  <div class="form-group">
      <div class="form-line">
          <input value="<?php echo $model->code; ?>" name="Project[code]" id="Project_code" type="text" class="form-control" placeholder="">
          <?php echo $form->error($model,'code', array('class'=>'error')); ?>
          
      </div>
  </div>  


  <label for="Project_name">*Nombre</label>
  <div class="form-group">
      <div class="form-line">
          <input value="<?php echo $model->name; ?>" name="Project[name]" id="Project_name" type="text" class="form-control" placeholder="">
          <?php echo $form->error($model,'name', array('class'=>'error')); ?>
          
      </div>
  </div>  


  <label for="Project_address">*Dirección</label>
  <div class="form-group">
      <div class="form-line">
          <input value="<?php echo $model->address; ?>" name="Project[address]" id="Project_address" type="text" class="form-control" placeholder="">
          <?php echo $form->error($model,'address', array('class'=>'error')); ?>
          
      </div>
  </div>  


  <label for="Project_location">*Plaza</label>
  <div class="form-group">
      <div class="form-line">
          <input value="<?php echo $model->location; ?>" name="Project[location]" id="Project_location" type="text" class="form-control" placeholder="">
          <?php echo $form->error($model,'location', array('class'=>'error')); ?>
          
      </div>
  </div>  

    <?php echo CHtml::submitButton($model->isNewRecord ? 'Crear' : 'Guardar', array('class'=>'btn btn-raised btn-primary m-t-15 waves-effect')); ?>
    <?php echo CHtml::link('Cancelar', Yii::app()->createUrl('project/admin') ,array('class'=>'btn btn-raised btn-primary m-t-15 waves-effect')); ?>

<?php $this->endWidget(); ?>

              </div>
          </div>
      </div>
  </div>

protected/views/project/_search.php
<?php
/* @var $this ProjectController */
/* @var $model Project */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'code'); ?>
		<?php echo $form->textField($model,'code',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'address'); ?>
		<?php echo $form->textField($model,'address',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'location'); ?>
		<?php echo $form->textField($model,'location',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/project/_view.php
<?php
/* @var $this ProjectController */
/* @var $data Project */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('code')); ?>:</b>
	<?php echo CHtml::encode($data->code); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('address')); ?>:</b>
	<?php echo CHtml::encode($data->address); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('location')); ?>:</b>
	<?php echo CHtml::encode($data->location); ?>
	<br />


</div>

protected/views/project/admin.php
<title>SIDIC - Proyectos</title>
<div class="row">
	<div class="col-md-12">
    <h3 style="margin-top:0px;">Proyectos</h3>
<?php $access=User::getPrivileges(); ?>
<?php if(Yii::app()->user->checkAccess('admin') || $access["crearProyecto"]): ?>
		<a class="btn btn-primary" href="<?php echo Yii::app()->createUrl('project/create'); ?>" 
			role="button">Crear Proyecto</a>
<?php endif; ?>			

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'project-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'cssFile'=>Yii::app()->theme->baseUrl.'/assets/cgridview/styles.css',
	'columns'=>array(
		'code',
		'name',
		'address',
		'location',
		array(
			'class'=>'CButtonColumn',
			'buttons'=>array(
				'update' => array(
				    //'label'=>'...',     // text label of the button
				    //'url'=>'...',       // a PHP expression for generating the URL of the button
				    //'imageUrl'=>false,  // image URL of the button. If not set or false, a text link is used
				    //'options'=>array('class'=>'btn btn-raised btn-primary m-t-15 waves-effect'), // HTML options for the button tag
				    //'click'=>'...',     // a JS function to be invoked when the button is clicked
				    'visible'=>Yii::app()->user->checkAccess('admin')==true?'true':'false',   // a PHP expression for determining whether the button is visible
				),	

				'delete' => array(
				    //'label'=>'...',     // text label of the button
				    //'url'=>'...',       // a PHP expression for generating the URL of the button
				    //'imageUrl'=>'...',  // image URL of the button. If not set or false, a text link is used
				    //'options'=>array(...), // HTML options for the button tag
				    //'click'=>'...',     // a JS function to be invoked when the button is clicked
				    'visible'=>'false',   // a PHP expression for determining whether the button is visible
				),	
				'view' => array(
				    //'label'=>'Ver presupuesto',     // text label of the button
				    'url'=>'Yii::app()->controller->createUrl("budget/list",array("id"=>$data->primaryKey))',       // a PHP expression for generating the URL of the button
				    //'imageUrl'=>false,  // image URL of the button. If not set or false, a text link is used
				    //'options'=>array(...), // HTML options for the button tag
				    //'click'=>'...',     // a JS function to be invoked when the button is clicked
				    'visible'=>'true',   // a PHP expression for determining whether the button is visible
				)			
			),
		),
	),
)); ?>

	</div>
</div>

protected/views/project/create.php
<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/project/index.php
<?php
/* @var $this ProjectController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Projects',
);

$this->menu=array(
	array('label'=>'Create Project', 'url'=>array('create')),
	array('label'=>'Manage Project', 'url'=>array('admin')),
);
?>

<h1>Projects</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/project/update.php
<?php
/* @var $this ProjectController */
/* @var $model Project */

$this->breadcrumbs=array(
	'Projects'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Project', 'url'=>array('index')),
	array('label'=>'Create Project', 'url'=>array('create')),
	array('label'=>'View Project', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Project', 'url'=>array('admin')),
);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/project/view.php
<?php
/* @var $this ProjectController */
/* @var $model Project */

$this->breadcrumbs=array(
	'Projects'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Project', 'url'=>array('index')),
	array('label'=>'Create Project', 'url'=>array('create')),
	array('label'=>'Update Project', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Project', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Project', 'url'=>array('admin')),
);
?>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'code',
		'name',
		'address',
		'location',
	),
)); ?>