protected/controllers/PrivilegesController.php
<?php
class PrivilegesController extends Controller {
	public $layout = '//layouts/admin';

	// Uncomment the following methods and override them if needed
	public function filters() {
		return array(
			'accessControl',
		  'ajaxOnly + removeAllItems + getOperations + remove',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 *
	 * @return array access control rules
	 */
	public function accessRules() {
		return array(
			array(
				'allow', // deny all users
				'actions' => array('index', 'update', 'getOperations', 'remove', 'RemoveAllItems'),
				'roles' => array(
					'admin' 
				) 
			),
			array(
				'deny', // allow all users to perform 'index' and 'view' actions
				'users' => array(
					'*' 
				) 
			) 
		);
	}

	public function actionIndex() {
		$licensekey = Yii::app()->user->getState('licensekey');
		$users = User::Model()->findAll("licensekey='".$licensekey."'");
		$auth = Yii::app()->authManager;
		$roles = $auth->getRoles();
		
		$this->render('index', array(
			'users' => $users,
			'roles' => $roles 
		));
	}

	public function actionUpdate() {
		$auth = Yii::app()->authManager;
		$roles = $auth->getRoles();
		$userid = 0;
		$extraPrivileges = null;
		
		if(isset($_POST["Privileges"]) && isset($_POST["Privileges"]['userid'])){
			$userid = $_POST["Privileges"]['userid'];
			if(isset($_POST["Privileges"]['extra'])){
				$extraPrivileges = $_POST["Privileges"]['extra'];
			}
		}
		
		// remover roles al usuario
		foreach ( $roles as $rol ){
			$auth->revoke($rol->name, $userid);
		}
		
		// remover operaciones al usuario
		$operations = $auth->getOperations();
		foreach ( $operations as $operation ){
			if(!isset($extraPrivileges)){
				$auth->revoke($operation->name, $userid);
			}
			else if(isset($extraPrivileges) && !in_array($operation->name, $extraPrivileges)){
				$auth->revoke($operation->name, $userid);
			}
		}
		
		$newRole = $this->extractRole($_POST["Privileges"]);
		$newOperation = $this->extractOperations($_POST["Privileges"]);
		
		// asignar nuevo rol + operaciones del rol
		foreach ( $newRole as $role ){
			$auth->assign($role, $userid);
			$children = $auth->getItemChildren($role . "Tarea");
			
			foreach ( $children as $item ){
				if(!$auth->isAssigned($item->name, $userid))
					$auth->assign($item->name, $userid);
			}
		}
		
		// asignar nuevas operaciones o permisos
		foreach ( $newOperation as $operation ){
			if(!$auth->isAssigned($operation, $userid))
				$auth->assign($operation, $userid);
		}
		
		$this->redirect(Yii::app()->createUrl('privileges/index'));
	}

	private function extractRole($roles) {
		$result = Array();
		if(isset($roles['role'])){
			foreach ( $roles['role'] as $item ){
				if(isset($item))
					array_push($result, $item);
			}
		}
		
		return $result;
	}

	private function extractOperations($operations) {
		$result = Array();
		if(isset($operations['operation'])){
			foreach ( $operations['operation'] as $item ){
				if(isset($item)){
					array_push($result, $item);
				}
			}
		}
		
		return $result;
	}

	/**
	 * Obtener todas las operaciones de todos los roles que no estén asignadas al usuario seleccionado
	 *
	 * @param
	 *        	Usuario Id es el id del usuario del que se van a obtener sus operaciones
	 */
	private function getAllOperations($userid) {
		$auth = Yii::app()->authManager;
		$rbac = Array();
		$operations = Array();
		$allOperations = Array();
		
		$operations = $auth->getOperations();
		
		foreach ( $operations as $item ){
			if(!$auth->isAssigned($item->name, $userid)){
				array_push($allOperations, $item->name);
			}
		}
		
		return $this->operationsToHTML($allOperations);
	}

	/**
	 * Obtener las operaciones por usuario
	 *
	 * @param
	 *        	Usuario Id es el id del usuario del que se van a obtener sus operaciones
	 */
	public function actionGetOperations($userid) {
		$userModel = User::Model()->findByPk($userid);
		$licensekey = Yii::app()->user->getState('licensekey');
		
		if($licensekey != $userModel->licensekey){
			$respuesta["data"] = "Usted no cuenta con privilegios.";
			echo json_encode($respuesta);
			return;
		}
		
		$auth = Yii::app()->authManager;
		$rolesList = $auth->getRoles($userid);
		
		$rbac = Array();
		$roles = Array();
		
		foreach ( $rolesList as $item ){
			array_push($roles, $item->name);
		}
		
		$rbac[0] = $roles;
		$rbac[1] = $this->getAllPrivilegesAllRoles($userid); // roles y privilegios
		$rbac[2] = $this->getAllOperations($userid);
		
		echo json_encode($rbac);
	}

	/**
	 * Crea un listado de operaciones en formato html
	 * basado en un arreglo de operaciones asignadas al usuario
	 *
	 * @param
	 *        	Operaciones
	 */
	private function operationsToHTML($operaciones) {
		$html = "";
		$i = 0;
		$id = "";
		$checked = "";
		
		foreach ( $operaciones as $item ){
			$id = "privilege_" . ++$i;
			$checked = "";
			if($item[0] == "1"){
				$checked = 'checked="checked"';
			}
			
			$html .= '<div class="item">
			<input ' . $checked . ' type="checkbox" id="' . $id . '" value="' . $item . '" name="Privileges[operation][' . $i . ']">&nbsp;' . $item . '<br/></div>';
		}
		
		return $html;
	}

	/**
	 * Regresa en formato html todos los privilegios de todos los roles del usuario seleccionado
	 *
	 * @param
	 *        	Usuario Id
	 */
	private function getAllPrivilegesAllRoles($userid) {
		$auth = Yii::app()->authManager;
		$authItems = $auth->getAuthItems(2, $userid);
		$operations = $auth->getOperations($userid);
		$permisos = "";
		
		if(sizeof($operations) == 0){
			return "";
		}
		
		foreach ( $authItems as $item ){
			$permisos .= "PARENT|<b>$item->name</b>";
			$children = $auth->getItemChildren($item->name . "Tarea");
			
			foreach ( $children as $child ){
				if($auth->isAssigned($child->name, $userid)){
					$permisos .= ";CHILD|" . $child->name;
				}
			}
			if(sizeof($children) > 0){
				$permisos .= ";";
			}
		}
		
		$tag = "";
		foreach ( $operations as $operation ){
			$tag = $operation->name;
			if(strpos($permisos, $tag) == false){
				$permisos .= ";CHILD|" . $tag . "_extra";
			}
		}
		
		return $permisos;
	}

	/**
	 * Remueve un privilegio al usuarios
	 *
	 * @param
	 *        	Name es el nombre del privilegio a remover
	 * @param
	 *        	User Id es el id del usuario que tiene asignado el privilegio
	 */
	public function actionRemove($itemname, $userid) {
		$auth = Yii::app()->authManager;
		$auth->revoke($itemname, $userid);
		$rbac = $this->getAllOperations($userid);
		
		echo json_encode($rbac);
	}

	/**
	 * Remueve varios privilegios de un usuario
	 *
	 * @param
	 *        	Items son los items a eliminar
	 * @param
	 *        	User Id es el id del usuario que tiene asignado el privilegio
	 */
	public function actionRemoveAllItems($userid) {
		$userModel = User::Model()->findByPk($userid);
		$licensekey = Yii::app()->user->getState('licensekey');
		
		if($licensekey != $userModel->licensekey){
			$respuesta["data"] = "Usted no cuenta con privilegios.";
			echo json_encode($respuesta);
			return;
		}
		
		if(isset($_POST["items"])){
			$auth = Yii::app()->authManager;
			$items = $_POST["items"];
			foreach ( $items as $itemName ){
				$auth->revoke($itemName, $userid);
			}
		}
	}
}

protected/views/privileges/_roles.php
<?php 

$i=0;
foreach ($data as $item) {
	$id='role_'.$i++;
	?>
  <div class="row rolerow" id="row<?php echo $id; ?>">
    <div class="item" id="<?php echo $id; ?>">
      <input type="checkbox" id="chkRole<?php echo $item->name; ?>"
             value="<?php echo $item->name; ?>" 
             name="Privileges[role][<?php echo $i; ?>]"
             />
    <?php echo $item->name; ?>
    </div>
  </div>
  <?php
}

?>

protected/views/privileges/_users.php
<?php 

foreach ($data as $item) {
	$id='user_'.$item->id;
	?>
  <div class="row userrow" id="<?php echo $id; ?>">
    <div class="col-md-8 col-sm-8 col-xs-8 col-lg-8">
      <div class="item"><?php echo $item->username.'<br/>'; ?></div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4 text-right">
      <a class="userrowver" href="#" onclick=
                  "getPrivileges(<?php echo $item->id; ?>, 
                  '<?php echo trim($item->username); ?>', '<?php echo $id; ?>'); return false;">
        ver
      </a>
    </div>
  </div>
  <?php
}
?>

<script type="text/javascript">


</script>

protected/views/privileges/index.php
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <input style="display:none;" id="btnPrivilegesGuardar" type="button" onclick="confirmationSaving();" 
       class="btn btn-raised btn-primary m-t-15 waves-effect btn-sm" value="Guardar"></input>	
	</div>

	<div class="col-md-12">
    <h3 style="margin:0px;">Derechos de usuario</h3>
    <small>Haga clic en la opci&oacute;n <i>"ver"</i> para ver los permisos asignados a cada usuario.</small>

<form name="PrivilegesForm" method="POST" action="<?php echo Yii::app()->createUrl('privileges/update'); ?>">

<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 col-lg-3 col-sm-12 col-xs-12">
			<h5>Usuarios:</h5>
			<input type="hidden" id="Privileges_userid" name="Privileges[userid]" value="">
			<div id="userlist">
				<?php 
						$this->renderPartial('_users', array(
							'data'=>$users,
						));
				?>
			</div>
		</div>

		<div class="col-md-4 col-lg-3 col-sm-12 col-xs-12">
			<h5>Roles:</h5>
			<div id="roleslist">
				<?php 
						$this->renderPartial('_roles', array(
							'data'=>$roles,
						));
				?>
			</div>
			<br/><h5>Permisos asignados:</h5>
			<button style="width:100%; display:none;" type="button" id="btnRemExtraPriv" onclick="removeAllExtraItem();" class="btn btn-warning btn-xs">Quitar permisos adicionales</button>
			<div id="rolesYPermisosList">
			</div>
		</div>

		<div class="col-md-4 col-lg-6 col-sm-12 col-xs-12">
			<div class="row">
			  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			    <h5>
<a hrerf="#" id="aditionprivilegeshelp" 
data-toggle="popover" title="Informaci&oacute;n" 
                   data-content="Son permisos adicionales al rol, que pueden ser asignados al usuario."
type="button" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span></a>
            Permisos adicionales:&nbsp;&nbsp;
			    	    <input id="checkPrivileges" type="checkbox" onclick="privilegesCheckAll(this);" />
			    	  &nbsp;Seleccionar todos / ninguno</h5>
			  </div>
			</div>
			<div id="privilegeslist">
			</div>
		</div>  
  </div>
</div>

</form>

	</div>
</div>

<style type="text/css">
	#userlist{height: 568px; border:1px #cecece solid; overflow: auto; padding:0;}
	#privilegeslist{height: 400px; border:1px #cecece solid; overflow: auto; padding:0;width: 100%}
	#roleslist{height: auto; border:1px #cecece solid; overflow: auto; padding:0;}
	#rolesYPermisosList{height: 400px; border:1px #cecece solid; overflow: auto; padding:0;}
	#userlist div.item{padding:3px 0; cursor:pointer;}
	#privilegeslist div.item{padding:0 3px;}
	#roleslist div.item{padding:0 3px;}
	#rolesYPermisosList div.item{padding:0 3px;}
  #checkPrivileges{margin:0px;}
  #userlist div.userrow:hover{background:#d0edf1 !important;}
  #userlist a.userrowver:hover{color:navy; font-weight: 700;}
  .removeitem{cursor:pointer;color:red;}
</style>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
  	$('#aditionprivilegeshelp').popover({placement:"top"});
    localStorage.removeItem("username");
  });

	function confirmationSaving(){
    if(localStorage.getItem("username")==null){
      bootbox.alert("Para poder guardar debe modificar los derechos de un usuario por lo menos.");
      $('#btnPrivilegesGuardar').css('display','none');
    }else{
      var rolesSelected=$('#roleslist div.rolerow input:checkbox').is(':checked');
      var _message="¿Desea guardar los privilegios para el usuario: "+localStorage.getItem("username")+" ?";

      if(!rolesSelected){
        _message="<div class=\"alert alert-warning\" role=\"alert\">El usuario <i>"+localStorage.getItem("username")+"</i> no tiene ning&uacute;n rol asignado, ¿Desea continuar con el guardado?</div>";
      }

	    bootbox.confirm({
	      message: _message,
	      buttons: {
	        confirm: {
	          label: 'Si',
	          className: 'btn-success'
	        },
	        cancel: {
	          label: 'No',
	          className: 'btn-danger'
	        }
	      },
	      callback: function (result) {
	      	if(result){
	      		$('#btnPrivilegesGuardar').css('display','none');
	      		document.forms.PrivilegesForm.submit();
	      	}
	      }
	    });
    }
	}

	function privilegesCheckAll(caller){
		$('#privilegeslist div.item input:checkbox').prop('checked', caller.checked);
	}

	function getAllOperations(userid){
    $('.rolerow').css('background','transparent');
    $.ajax({
      type: 'GET',
      async: true,
      contentType: "application/json",
      url: "<?php echo Yii::app()->createUrl('/privileges/getAllOperations').'&userid='; ?>"+userid,
      success: function(data){
        privileges=JSON.parse(data)[0];
      },
      error: function(jqXHR, textStatus, errorThrown){
        alert("Se ha interrumpido la conexión de red.");
      },
    });		
	}

  function repaint(rowid){
    $('.userrow').css('background-color','white');
    $('#'+rowid).css('background-color','#60ccda !important');
  }

  function getPrivileges(userid, username, rowid){
  	repaint(rowid);
  	localStorage.setItem("username", username);
  	localStorage.setItem("userid", userid);
  	$('#Privileges_userid')[0].value=userid;
    $.ajax({
      type: 'GET',
      async: true,
      contentType: "application/json",
      url: "<?php echo Yii::app()->createUrl('/privileges/getOperations').'&userid='; ?>"+userid,
      success: function(data){
        json=JSON.parse(data);
        $('#btnPrivilegesGuardar').css('display','block');
        rolesYPermisosListPopulate(json[1], userid);
        checkPrivileges(JSON.parse(data)[2]);
        checkRoles(data);
      },
      error: function(jqXHR, textStatus, errorThrown){
        alert("El servidor no pudo procesar la solicitud.");
      },
    });
  }

  function checkRoles(data){
    roles=JSON.parse(data)[0];
  	$('#roleslist div.item input:checkbox').prop('checked', false);

    for (var i = 0; i < roles.length; i++) {
	    $('#chkRole'+roles[i]).prop('checked', true);
    }
  }

  function checkPrivileges(data){
  	unassignedop=data;
    $('#privilegeslist').html(unassignedop);
  }

  function rolesYPermisosListPopulate(data, userid){
    $('#rolesYPermisosList').html("");
    $('#btnRemExtraPriv').hide();
    if(jQuery.trim(data).length==0)
      return;
    data=data.split(";");
    var _innerHTML="";
    var extraPrivTitle="";

    for (var i = 0; i < data.length; i++) {
      if(data[i].split("|")[0]=="PARENT"){
        _innerHTML+="<div>"+data[i].split("|")[1]+"</div>";
      }else if(data[i].split("|")[1]!=undefined){
        var dato=data[i].split('|')[1];
        var click='removeExtraItem(\"'+dato.replace("_extra","")+'\",'+userid+', this);';
        var span="";

        if(dato.indexOf("_extra")!=-1){
          if(extraPrivTitle==""){
            extraPrivTitle="<div class='extraPrivTitle'><b>Permisos adicionales</b></div>";
            _innerHTML+=extraPrivTitle;
          }
          $('#btnRemExtraPriv').show();
          span="<input type='hidden' name='Privileges[extra]["+i+"]' value='"+dato.replace("_extra","")+"' /><span onclick='"+click+"' title='Quitar Permiso' class='removeitem'>[ X ]</span>&nbsp;";
        }
        if(dato.indexOf("_extra")!=-1){
         _innerHTML+="<div class='aditionalPrivilegeItem'>&nbsp;"+span+"<span class='aditionalPrivilege'>"+dato.replace("_extra","")+"</span></div>";
        }else{
          _innerHTML+="<div>&nbsp;"+span+dato.replace("_extra","")+"</div>";
        }
      }
    }
    $('#rolesYPermisosList').html(_innerHTML);
  }

  function removeExtraItem(itemname, userid, caller){
    bootbox.confirm({
      message: "¿Desea remover el permiso <b><i>"+itemname+"</i></b> ?: ",
      buttons: {
        confirm: {
          label: 'Si',
          className: 'btn-success'
        },
        cancel: {
          label: 'No',
          className: 'btn-danger'
        }
      },
      callback: function (result) {
      	if(result){
			    $.ajax({
			      type: 'GET',
			      async: true,
			      contentType: "application/json",
			      url: "<?php echo Yii::app()->createUrl('privileges/remove'); ?>"+"&itemname="+itemname+"&userid="+userid,
			      success: function(data){
			        caller.parentElement.remove();
              if($('.aditionalPrivilegeItem').length==0){
                $('.extraPrivTitle').remove();
                $('#btnRemExtraPriv').hide();
              }

			        checkPrivileges(JSON.parse(data));
			      },
			      error: function(jqXHR, textStatus, errorThrown){
			        alert("El servidor no pudo procesar la solicitud.");
			      },
			    });
      	}
      }
    });
  }

  function removeAllExtraItem(){
    bootbox.confirm({
      message: "¿Desea remover <b>todos</b> los permisos adicionales del usuario: <i>"+localStorage.getItem("username")+"</i>?",
      buttons: {
        confirm: {
          label: 'Si',
          className: 'btn-success'
        },
        cancel: {
          label: 'No',
          className: 'btn-danger'
        }
      },
      callback: function (result) {
      	var _items=Array();
				$('.aditionalPrivilege').each(function(){
				  _items[_items.length]=this.innerText;  
				});

      	if(result){
			    $.ajax({
			      type: 'POST',
			      async: true,
			      data: {items:_items},
			      url: "<?php echo Yii::app()->createUrl('privileges/removeallitems'); ?>"+"&userid="+localStorage.getItem("userid"),
			      success: function(data){
              $('#btnRemExtraPriv').hide();
              $('.aditionalPrivilegeItem').remove();
			        $('.extraPrivTitle').remove();
      				Notify({
								content: 'Permisos adicionales fueron removidos.',
								rounded: true,
								color: '#dff0d8'
							});
			      },
			      error: function(jqXHR, textStatus, errorThrown){
			        alert("El servidor no pudo procesar la solicitud.");
			      },
			    });
      	}
      }
    });
  }

</script>

<script src="https://malsup.github.io/jquery.blockUI.js"></script>
<script src="<?php echo Yii::app()->theme->baseUrl;?>\assets\bootbox.min.js"></script>
<script src="<?php echo Yii::app()->baseUrl.'/protected/vendor/jquerytoast/notify.min.js'; ?>"></script>
<script src="<?php echo Yii::app()->baseUrl.'/protected/vendor/tooltip/tooltip.min.js'; ?>"></script>
      